# -*- coding: utf-8 -*-
"""orbit_sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGjebycnaMp3BZSa_5Xn82YKXt0LOs5E
"""

import numpy as np
import matplotlib.pyplot as plt

# Constants
G = 6.674e-11      # gravitational constant (m^3 kg^-1 s^-2)
M = 5.972e24       # mass of Earth (kg)
R = 6.371e6        # radius of Earth (m)

# Initial conditions
r0 = np.array([R + 400e3, 0])   # 400 km altitude
v0 = np.array([0, 7700])        # ~7.7 km/s orbital speed

dt = 1       # timestep (s)
t_max = 6000 # total simulation time (s)
steps = int(t_max / dt)

r, v = r0, v0
positions = []

r = r.astype(float)
v = v.astype(float)
dt = float(dt)


for _ in range(steps):
    r_mag = np.linalg.norm(r)
    a = -(G * M / r_mag**3) * r  # acceleration
    v += a * dt
    r += v * dt
    positions.append(r.copy())

positions = np.array(positions)

# Plot orbit
plt.figure(figsize=(6,6))
plt.plot(positions[:,0], positions[:,1], label="Satellite path")
plt.plot(0, 0, 'ro', label="Earth center")
plt.gca().set_aspect('equal')
plt.title("Satellite Orbit Simulation")
plt.legend()
plt.xlabel("X position (m)")
plt.ylabel("Y position (m)")
plt.show()
